# Generated by Django 5.0.1 on 2024-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
